version: '3.8'

services:
  gmail-digest-bot:
    build: .
    ports:
      - "8000:8000"
    environment:
      - FLASK_SECRET_KEY=${FLASK_SECRET_KEY:-dev-secret-change-me}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GMAIL_REFRESH_TOKEN=${GMAIL_REFRESH_TOKEN}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - X_API_KEY=${X_API_KEY:-dev-api-key}
      - COSMOS_URL=${COSMOS_URL}
      - COSMOS_KEY=${COSMOS_KEY}
      - COSMOS_DB=${COSMOS_DB:-GmailDigest}
      - COSMOS_CONTAINER=${COSMOS_CONTAINER:-Data}
      - SENDGRID_API_KEY=${SENDGRID_API_KEY}
      - TZ=${TZ:-America/Los_Angeles}
    volumes:
      - ./app:/app
      - ./web/dist:/app/static/dist
    restart: unless-stopped

